version: '3'
services:
  maplestory:
    container_name: maplestory
    build: .
    depends_on:
      - db
    environment:
      TZ: "Asia/Shanghai"
      WAIT_HOSTS: db:3306
    ports:
      - 8484:8484
      - 7575:7575
      - 7576:7576
      - 7577:7577
    
  db:
    container_name: maplestory-db
    image: mysql:5.6
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "heavenms"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
